# Function algorithm generated by GitHub Copilot
def deep_merge(*dicts):
    """
    Recursively merges an arbitrary number of dictionaries and returns a new dictionary with the
    result. Does not modify the input dictionaries. Dictionaries are merged left to right, with
    later dictionaries overriding values from earlier ones.

    Args:
        *dicts: Variable number of dictionaries to merge.

    Returns:
        dict: The merged dictionary.
    """
    if not dicts:
        return {}

    if len(dicts) == 1:
        return dicts[0].copy() if dicts[0] else {}

    # Start with a copy of the first dictionary
    result = dicts[0].copy() if dicts[0] else {}

    # Merge each subsequent dictionary
    for current_dict in dicts[1:]:
        if not current_dict:
            continue

        for key, value in current_dict.items():
            if (
                key in result
                and isinstance(result[key], dict)
                and isinstance(value, dict)
            ):
                result[key] = deep_merge(result[key], value)
            else:
                result[key] = value

    return result
